### ISSUE TITLE
[9.5~10.24] ETRI 오픈 API 활용사례 공모전

### ISSUE THREAD

**Issue by Paul-scpark** [Paul-scpark/AI-dev-course#10]
### 공모주제
1. 국내 인공지능 응용개발 및 산업 생태계 활성화를 위해 개발된 ETRI 오픈 API의 활용
및 확산을 위해 ETRI 오픈 API/학습데이터/학습 모델을 활용한 우수사례 발굴
2. ETRI 오픈 API/학습데이터/학습모델을 활용한 사례

### 일정
1. 참가 신청 접수: 9.5 ~ 10.24
2. 결과물 제출 기간: 10.3 ~ 10.31
3. 수상자 발표: 11월 중순
4. 시상 및 시연: 12월 중 (별도 안내 공지)

### 시상 내역
- 대상: 과기부장관상 1팀, 300만원
- 최우수상: 과기부장관상 1팀, 200만원
- 우수상: ETRI 원장상 1팀, 100만원
- 장려상: ETRI 원장상 2팀, 50만원

### 데이터
- ETRI 오픈 API, 학습데이터, 학습 모델

**Comment by BBARRY-Lee** [comment]
안녕하세요

**Comment by augustinLib** [comment]
test
